name: gft2
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.4
  - numpy=1.20
  - nilearn=0.9
  - pandas=1.2
  - python=3.9
  - scipy=1.8
  - tqdm
  - scikit-learn=1.0
  - mne=1.0
  - git
  - joblib
  - r-base=4.1
  - r-essentials
  - pip
  - pip:
    - mne_bids==0.10
    - notebook==6.4
    - h5io==0.1.7
    - cmake
    - pybv>=0.6
